name: iOS binary build & upload to TestFlight

on:
  workflow_dispatch:
  pull_request:
    branches:
      - release

jobs:
  distribute:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      - name: Create .env file
        run: |
          echo "${{ secrets.APP_ENV_FILE }}" > .env.default

      - name: Install bundler
        run: gem install bundler

      - name: Install fastlane dependencies
        run: bundle install

      - name: clean pod cache
        run: |
          pod cache clean --all
          pod install

      - name: Set up SSH for match
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_PRIVATE_KEY }}" > ~/.ssh/ci_match_key
          chmod 600 ~/.ssh/ci_match_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "Host github.com" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/ci_match_key" >> ~/.ssh/config
          
      - name: Build & upload iOS binary
        run: |
          pod install --repo-update 
          bundle exec fastlane build_upload_testflight
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.ASC_PRIVATE_KEY }}