name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  
jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: SetupLastXcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Install Bundler
        run: gem install bundler -v 1.17.2

      - name: Install gems
        run: bundle install

      - name: Run Tests
        run: bundle exec fastlane unit_test